### PR TITLE
Expose client

### PR DESCRIPTION
**Pull request by goofmint**
Exposing HexabaseClient for more useful developers. Those are sample code using Hexabase with Vue3 store.

```js
import { HexabaseClient } from "@hexabase/hexabase-js";
// Token name for localStorage
const tokenName = "hexabaseToken";
// Get token from localStorage
const token = localStorage.getItem(tokenName);
// GraphQL endpoint
const url = "https://graphql.hexabase.com/graphql";

export const useHexabaseClient = defineStore("hexabase", () => {
  // Create a new HexabaseClient
  const hexabase = ref(new HexabaseClient(url, token || undefined));
  // Call this method when user logged in
  const setToken = ref((token: string) => {
    // Set token to HexabaseClient
    hexabase.value.setToken(token!);
    // Save token to localStorage
    localStorage.setItem(tokenName, token!);
  });
  return { setToken, hexabase };
});
```

### CODE REVIEW

**Review by okamura-asnet — COMMENTED** [review]
@goofmint 
Thank you!!
I will share the source code at the time of verification below.

I think the token should be automatically set when the login is successful. What do you think?

```
  const test = async () => {
    // ------------------------------
    // initialize
    // ------------------------------
    const hexabaseClient = new HexabaseClient(
      "https://hxb-graph.hexabase.com/graphql"
    );

    // ------------------------------
    // login
    // ------------------------------
    const { token, error } = await hexabaseClient.auth.login({
      email: email,
      password: password,
    });

    // *** I think it would be better if this step is not necessary. ***
    // set token
    hexabaseClient.setToken(token);
    // ******

    // ------------------------------
    // [Workspace]
    // ------------------------------
    // ・get single
    const response_workspaces_get_single = await hexabaseClient.workspaces.get("WORKSPACE_ID");
  };
```

**Comment by goofmint** [comment]
@okamura-asnet 

> I think the token should be automatically set when the login is successful. What do you think?

I think it's nice. However, the developers have to save the token to localStorage or somewhere. So the SDK has to return the token even if the SDK sets the token automatically.

This is firebase's example.

[Auth state persistence  |  Firebase](https://firebase.google.com/docs/auth/web/auth-state-persistence)

The developers can control auth state.

 - memory:  
The token revokes if the browser's tab is closed.
- session:
Token revokes if the browser reloaded.
- local:
The token is saved in localStorage

If the developers select "local", the SDK will be saved the token to localStorage automatically. They don't care about saving the token.

**Review by okamura-asnet — APPROVED** [review]
@goofmint 
Thank you so much for your careful checking.

> So the SDK has to return the token even if the SDK sets the token automatically.
I think so, too.
I think that's the desired behavior from the developers about the return value of the login method.

I would like to reconsider where to automatically save the token.

LGTM!!

**Comment by BanND99** [comment]
Sorry to bother you. I do the similar way in `nuxt3 `width `pinia `store. The problem is when I call the `hexabase `object from store, only static value is retrieved, all methods formed as prototypes are gone. I would see it as normal behavior when it not allowed to stored stuff other than static properties. Please advices!

**Comment by BanND99** [comment]
the store I create in nuxt as bellow: 
```
import {defineStore} from 'pinia'
import {createClient} from "@hexabase/hexabase-js";
import HexabaseClient from "@hexabase/hexabase-js/dist/HexabaseClient";

export const useHexabaseClient = defineStore("haxabaseClient", {
    state: () => {
        return {
            hexabase: {} as HexabaseClient
        }
    },
    actions: {
      async updateHxbClient({url, token}: {url: string, token: string}){
          if( { url, token } ){
              this.hexabase = await createClient({url, token})
          }
      }
    },
    persist: true
})
```

**Comment by goofmint** [comment]
@BanND99 This is my example. 

https://github.com/hexabase/example-vue3-productmanager/blob/main/src/stores/hexabase.ts

**Comment by BanND99** [comment]
@goofmint I see that you set the token as string | undefined to create new HexabaseClient, but it doesn't work with undefinded token

**Comment by goofmint** [comment]
@BanND99 I didn't save the client variant as an object, only the token string. Maybe the `persist` option will be saved in localStorage, and they can't restore the data.

**Comment by BanND99** [comment]
@goofmint That why I have to re-create the Client variant to call other services. Do you have any idea to minimize the initialization of it, as mr.Jean desires to take that.

**Comment by goofmint** [comment]
@BanND99 I have no idea. So I don't use createClient with async. It has a lot of constraints.

**Pull request merged**
